export const ROOM_DEFS = [
  {
    id: 'riflessione',
    name: 'Riflessione',
    icon: '🔮',
    color: '#D8C7FF',
    colorDark: '#7C62D9',
    colorBg: '#F3EEFF',
    description: 'Pensieri profondi e introspezione',
    prompt: 'Come ti senti oggi davvero?',
    examples: ['Oggi ho capito che...', 'Mi sto chiedendo se...', 'Ho bisogno di riflettere su...'],
  },
  {
    id: 'quotidiano',
    name: 'Quotidiano',
    icon: '☀️',
    color: '#FFF3B0',
    colorDark: '#D9B82E',
    colorBg: '#FFFDF1',
    description: 'La tua giornata, momento per momento',
    prompt: 'Cosa è successo oggi?',
    examples: ['Stamattina...', 'Al lavoro oggi...', 'Stasera ho voglia di...'],
  },
  {
    id: 'gratitudine',
    name: 'Gratitudine',
    icon: '🪴',
    color: '#C8F7DC',
    colorDark: '#65AE82',
    colorBg: '#F0FFF6',
    description: 'Ciò per cui sei grato ogni giorno',
    prompt: 'Per cosa sei grato oggi?',
    examples: ['Sono grato per...', 'Mi ha fatto sorridere...', 'Ho apprezzato molto...'],
  },
  {
    id: 'sogni',
    name: 'Sogni',
    icon: '🌙',
    color: '#B3E5FF',
    colorDark: '#5E9BC8',
    colorBg: '#F2FAFF',
    description: 'Sogni notturni e desideri del cuore',
    prompt: 'Hai sognato stanotte?',
    examples: ['Ho sognato che...', 'Un giorno vorrei...', 'Mi immagino...'],
  },
  {
    id: 'sfoghi',
    name: 'Sfoghi',
    icon: '🔥',
    color: '#FFC9DE',
    colorDark: '#D986B0',
    colorBg: '#FFF4FA',
    description: 'Libera la pressione, senza giudizi',
    prompt: 'Cosa ti pesa in questo momento?',
    examples: ['Sono stufo di...', 'Non riesco a capire perché...', 'Ho bisogno di dire che...'],
  },
]
