export const ROOM_DEFS = [
  {
    id: 'riflessione',
    name: 'Riflessione',
    icon: '🔮',
    color: '#818cf8',
    colorDark: '#3730a3',
    colorBg: '#1e1b4b',
    description: 'Pensieri profondi e introspezione',
    prompt: 'Come ti senti oggi davvero?',
    examples: ['Oggi ho capito che...', 'Mi sto chiedendo se...', 'Ho bisogno di riflettere su...'],
  },
  {
    id: 'quotidiano',
    name: 'Quotidiano',
    icon: '☀️',
    color: '#fbbf24',
    colorDark: '#92400e',
    colorBg: '#1c1506',
    description: 'La tua giornata, momento per momento',
    prompt: 'Cosa è successo oggi?',
    examples: ['Stamattina...', 'Al lavoro oggi...', 'Stasera ho voglia di...'],
  },
  {
    id: 'gratitudine',
    name: 'Gratitudine',
    icon: '🌿',
    color: '#34d399',
    colorDark: '#065f46',
    colorBg: '#022c22',
    description: 'Ciò per cui sei grato ogni giorno',
    prompt: 'Per cosa sei grato oggi?',
    examples: ['Sono grato per...', 'Mi ha fatto sorridere...', 'Ho apprezzato molto...'],
  },
  {
    id: 'sogni',
    name: 'Sogni',
    icon: '🌙',
    color: '#c084fc',
    colorDark: '#581c87',
    colorBg: '#1a0533',
    description: 'Sogni notturni e desideri del cuore',
    prompt: 'Hai sognato stanotte?',
    examples: ['Ho sognato che...', 'Un giorno vorrei...', 'Mi immagino...'],
  },
  {
    id: 'sfoghi',
    name: 'Sfoghi',
    icon: '🔥',
    color: '#f87171',
    colorDark: '#7f1d1d',
    colorBg: '#1c0a0a',
    description: 'Libera la pressione, senza giudizi',
    prompt: 'Cosa ti pesa in questo momento?',
    examples: ['Sono stufo di...', 'Non riesco a capire perché...', 'Ho bisogno di dire che...'],
  },
]
